name: qstaple
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - altgraph=0.17.5=pyhd8ed1ab_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h33c6efd_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_17
  - libgomp=15.2.0=he0feb66_17
  - liblzma=5.8.2=hb03c661_0
  - libmpdec=4.0.0=hb03c661_1
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_17
  - libuuid=2.41.3=h5347b49_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0.1=pyh145f28c_0
  - pyinstaller=6.18.0=py314hda92701_0
  - pyinstaller-hooks-contrib=2026.0=pyhd8ed1ab_0
  - pypdf=6.6.2=pyhcf101f3_0
  - python=3.14.3=h32b2ec7_100_cp314
  - python_abi=3.14=8_cp314
  - readline=8.3=h853b02a_0
  - setuptools=80.10.2=pyh332efcf_0
  - tk=8.6.13=noxft_h366c992_103
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - zipp=3.23.0=pyhcf101f3_1
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/gsb/miniconda3/envs/qstaple
